title:            High-Dimensional Probability
email:            wessel.p.bruinsma@gmail.com
description:      Solutions for exercises from High-Dimensional Probability by Martin. J. Wainwright
url:              "https://high-dimensional-probability.github.io/"
baseurl:          
github_usename:   wesselb
google_analytics: UA-93527056-2

# Build settings
highlighter: rouge
markdown: kramdown
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.txt
    - README.md
    - link.py
    - todo.tasks

